version: '3'
services:
  
  web:
    build: webclient
    ports:
      - "8001:5000"
    environment:
      ZMQ_REQ_PORT: 3000

  server:
    build: server
    expose:
      - "3000"
    environment:
      ZMQ_BIND_PORT: 3000

  mongo:
    build: mongo
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

volumes:
  mongo_data:
  mongo_config:  
